### ISSUE TITLE
ReadMe needs an update

### ISSUE THREAD

**Issue by gdg4dev** [1pt-co/1pt#38]
The new endpoint is not working with the`''/addURL"` or `"/addURL.php"` route (the latter one is expected as the new one uses express, so it could be a problem with the backend?).

The old endpoint works but we need to add the `.php` file extension after `/addURL` path. I found this path by analyzing network requests on 1pt.co

**Comment by gdg4dev** [comment]
need to update the request method from `"GET"` to `"POST"` for new endpoint after reading the code from [here](https://github.com/1pt-co/api/blob/main/index.js#L32)

**Comment by paramt** [comment]
Good catch, thanks!
